export enum NodeType {
    PROGRAM = "PROGRAM", 
    VARDECL = "VARDECL", 
    FUNCDECL = "FUNCDECL", 
    PARAMETER = "PARAMETER",
    BLOCK = "BLOCK",
    ASSIGNMENT = "ASSIGNMENT", 
    CONDITIONAL = "CONDITIONAL", 
    WHILELOOP = "WHILELOOP", 
    RETURNSTMT = "RETURNSTMT",
    BREAKSTMT = "BREAKSTMT", 
    CONTINUESTMT = "CONTINUESTMT", 
    BINARYOP = "BINARYOP", 
    UNARYOP = "UNARYOP",
    LOCATION = "LOCATION", 
    FUNCCALL = "FUNCCALL", 
    LITERAL = "LITERAL"
}