export enum NodeType {
    PROGRAM, 
    VARDECL, 
    FUNCDECL, 
    BLOCK,
    ASSIGNMENT, 
    CONDITIONAL, 
    WHILELOOP, 
    RETURNSTMT,
    BREAKSTMT, 
    CONTINUESTMT, 
    BINARYOP, 
    UNARYOP,
    LOCATION, 
    FUNCCALL, 
    LITERAL
}